import type { Metadata } from "next";
import "./globals.css";
import ClientreduxProvider from "@/redux/clientreduxProvider";
import ThemeInitializer from '@/app/components/ThemeInitializer';
import { ToastProvider } from "@/app/components/ui/ToastProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ClientreduxProvider>
        <ToastProvider><ThemeInitializer />
        {children}
        </ToastProvider>
      </ClientreduxProvider></body>
    </html>
  );
}
